export const content = {
  en: {
    steps: [
      {
        question: "What type of business do you run?",
        bubbles: [
          "Restaurant",
          "Coffee Shop",
          "Bakery",
          "Pizzeria",
          "Clothing Store",
          "Cosmetics",
          "Hair Salon",
          "Shoe Store",
          "Grocery",
          "Retail",
          "Fruits & Vegetables",
          "Warehouse",
          "Laundry",
          "Studio",
          "Mini-Market",
          "Small Supermarket",
        ],
      },
      {
        question: "How is your business structured?",
        bubbles: [
          "Single Location",
          "Multiple Branches",
          "Family Business",
          "Large Business",
          "Small Business",
          "Franchise Branches",
          "Logistics Center",
          "Complex Operations",
          "Mostly Evening Activity",
          "Mostly Daytime Activity",
        ],
      },
      {
        question: "Who is your team?",
        bubbles: [
          "Full-time Employees",
          "Shift Workers",
          "Temporary Workers",
          "Shift Managers",
          "Delivery / Riders",
          "Solo Operator",
          "Family Staff",
          "Rotating Staff",
          "Large Team (10+)",
          "Small Team (1–4)",
        ],
      },
      {
        question: "What matters to you in camera monitoring?",
        bubbles: [
          "Theft",
          "Employees leaving early",
          "Staff behavior",
          "Busy hours",
          "Long queues",
          "Unauthorized entry",
          "Cleanliness",
          "Cashier area",
          "Work areas",
          "Storage area",
        ],
      },
      {
        question: "What do you want the AI to help with?",
        bubbles: [
          "Alert me when something is wrong",
          "Monitor service quality",
          "Provide daily reports",
          "Track staff activity",
          "Improve operational efficiency",
          "Help with task management",
          "Analyze the business",
          "Increase profitability",
        ],
      },
    ],
    next: "Next",
    back: "Back",
    finalMessage:
      "These settings are just to get started.\nYou can change everything anytime.",
    finalButton: "Let's Begin",
    progress: "Step",
    summaryIntro: "Here’s a quick summary of what you told us:",
    summaryStep1: "Your business type",
    summaryStep2: "Business structure",
    summaryStep3: "Your team",
    summaryStep4: "Camera focus",
    summaryStep5: "AI assistance",
    summaryNone: "No selections",
  },
  he: {
    steps: [
      {
        question: "איזה סוג עסק אתם מנהלים?",
        bubbles: [
          "מסעדה",
          "בית קפה",
          "מאפייה",
          "פיצרייה",
          "חנות בגדים",
          "קוסמטיקה",
          "מספרה",
          "חנות נעליים",
          "מכולת",
          "קמעונאות",
          "פירות וירקות",
          "מחסן",
          "כביסה",
          "סטודיו",
          "מיני-מרקט",
          "סופרמרקט קטן",
        ],
      },
      {
        question: "איך העסק שלכם מאורגן?",
        bubbles: [
          "סניף יחיד",
          "מספר סניפים",
          "עסק משפחתי",
          "עסק גדול",
          "עסק קטן",
          "סניפי זיכיון",
          "מרכז לוגיסטי",
          "תפעול מורכב",
          "פעילות ערבית בעיקר",
          "פעילות יומית בעיקר",
        ],
      },
      {
        question: "מי הצוות שלכם?",
        bubbles: [
          "עובדים במשרה מלאה",
          "עובדי משמרות",
          "עובדים זמניים",
          "מנהלי משמרת",
          "משלוחים / רוכבים",
          "עובד יחיד",
          "צוות משפחתי",
          "צוות מתחלף",
          "צוות גדול (10+)",
          "צוות קטן (1-4)",
        ],
      },
      {
        question: "מה חשוב לכם בניטור מצלמות?",
        bubbles: [
          "גניבות",
          "עובדים עוזבים מוקדם",
          "התנהגות צוות",
          "שעות עומס",
          "תורים ארוכים",
          "כניסה לא מורשית",
          "ניקיון",
          "אזור קופה",
          "אזורי עבודה",
          "אזור אחסון",
        ],
      },
      {
        question: "במה תרצו שה-AI יעזור לכם?",
        bubbles: [
          "להתריע כשמשהו לא תקין",
          "לנטר איכות שירות",
          "לספק דוחות יומיים",
          "לעקוב אחר פעילות צוות",
          "לשפר יעילות תפעולית",
          "לעזור בניהול משימות",
          "לנתח את העסק",
          "להגדיל רווחיות",
        ],
      },
    ],
    next: "הבא",
    back: "חזור",
    finalMessage: "ההגדרות האלו הן רק כדי להתחיל.\nאפשר לשנות הכל בכל רגע.",
    finalButton: "בואו נתחיל",
    progress: "שלב",
    summaryIntro: "הנה סיכום קצר של מה שסיפרת לנו:",
    summaryStep1: "סוג העסק שלך",
    summaryStep2: "מבנה העסק",
    summaryStep3: "הצוות שלך",
    summaryStep4: "מה חשוב לך במצלמות",
    summaryStep5: "איך ה-AI יכול לעזור לך",
    summaryNone: "לא נבחרו פריטים",
  },
};
